In [1]:
import numpy as np

Arquivo criado para **teste** de códigos para realização de jogadas, caso tenha um bom resultado, será implementado nos algoritmos de IA para realizar os testes das jogadas

In [2]:
# Função para verificar se as linhas são iguais
def verif_linhas(array):
    for linha in array:
        # Verificando se os elementos da linha são iguais exceto zero
        if (np.all(linha == 1) or np.all(linha == -1)) and np.any(linha != 0): 
           return linha[0] # Retornando o valor do ganhador: 1 ou -1
       
    return False

# Função para verificar se as colunas são iguais          
def verif_colunas(array):
    # Transpondo o array para verificar colunas como se fossem linhas
    for coluna in array.T:  
        # Verificando se os elementos da coluna são iguais exceto zero
        if (np.all(coluna == 1) or np.all(coluna == -1)) and np.any(coluna != 0): 
            return coluna[0] # Retornando o valor do ganhador: 1 ou -1
        
    return False

# Função para verificar se a diagonal principal são iguais
def verif_diag_principal(array):
    diagonal_principal = np.diag(array)  # Diagonal principal
    # Verificando se os elementos da diagonal principal são iguais exceto zero
    if (np.all(diagonal_principal == 1) or np.all(diagonal_principal == -1))  and np.all(diagonal_principal!=0) :
        return diagonal_principal[0] # Retornando o valor do ganhador: 1 ou -1
    
    return False

# Função para verificar se a diagonal secundária são iguais
def verif_diag_secundaria(array):
    diagonal_secundaria = np.diag(np.fliplr(array))  # Diagonal secundária (flipping array)
    # Verificando se os elementos da diagonal secundária são iguais exceto zero
    if (np.all(diagonal_secundaria == 1) or np.all(diagonal_secundaria==-1))  and np.all(diagonal_secundaria!=0): 
        return diagonal_secundaria[0] # Retornando o valor do ganhador: 1 ou -1
    
    return False

def get_vencedor(lista_respostas):
    for valor in lista_respostas:
        # Transormando cada valor em uma string, verifica-se se o valor é numérico (1 ou -1)
        valor = str(valor)
        if valor.isnumeric():
            # Condicional para determinar qual valor retorna
            if valor == "1":
                return "X"
            else:
                return "Y"

def status_jogo(jogada):
    # Conversão do array que está sendo usado como parâmetro em uma matriz de 3x3
    jogada = np.array(jogada).reshape(3,3)
    
    # Criando uma lista com os retornos das funções verificadoras de cada jogada, o resultado é um array de 4 elementos. Ex: [1,False,False,False]
    lista_resposta = list([verif_colunas(jogada), verif_linhas(jogada), verif_diag_principal(jogada), verif_diag_secundaria(jogada)])
    # Se algum dos elementos da lista for diferente de false, a função get_vencedor será chamada
    if any(lista_resposta):
        valor = get_vencedor(lista_resposta)
        return valor + " VENCEU!"
    # Condicional para verificar se os únicos valores preenchidos no tabuleiro são 1 e -1
    elif len(np.unique(jogada)) == 2 and 0 not in np.unique(jogada):
        return "EMPATE"
    else:
        return "AINDA TEM JOGO"

In [3]:
def get_tabuleiro(jogadas):
    # Função para imprimir o tabuleiro de Tic-Tac-Toe
    for i in range(0, 9, 3):
        linha = jogadas[i:i+3]
        print(' | '.join(linha))
        if i < 6:
            print("---------")  # Separador entre linhas

In [4]:
jogada = [0,1,0,0,1,1,-1,-1,0]
get_tabuleiro(list(map(str, jogada)))

0 | 1 | 0
---------
0 | 1 | 1
---------
-1 | -1 | 0


### **Funções para coleta e atualizações de jogadas**

In [5]:
def coleta_jogada():
    # Coletando os valores por meio de um input
    linha, coluna = input("Informe a linha e a coluna onde deseja incluir o x. Ex: [1,2]").split(",")
    
    # Convertendo os valores para inteiro
    return int(linha), int(coluna)


def ajuste_jogada(jogada,linha,coluna):
    # Subtraindo os valores das linhas ou colunas caso o valor seja maior que zero
    if linha != 0:
        linha -= 1

    if coluna != 0:
        coluna -= 1
        
    # print("Linha: {} Coluna: {}".format(linha,coluna))

    # Caso a posição informada pelo usuário não esteja preenchida, ele realiza a modificação
    if jogada[linha][coluna] != 0:
        print ("Já preenchido")
    else:
        jogada[linha][coluna] = 1
        print ("Jogada realizada")
        
    return jogada

In [6]:
# Convertendo a lista de jogadas em um array 3x3
jogada = np.array(jogada).reshape(3,3)

finalizar_jogo = False

print(jogada)
print("=====================================\n")

while not finalizar_jogo:
    # Coletando a jogada
    linha,coluna = coleta_jogada()
    
    # Realizando o ajuste da jogada a partir das posições de inserção informadas
    jogada = ajuste_jogada(jogada,linha,coluna)
    
    # Plotando o tabuleiro 
    # AQUI PRECISA DA FUNÇÃO BONITA PARA EXIBIR O TABULEIRO COM OS X E O
    print(jogada)
    
    
    # Obtenção do status do jogo
    print(status_jogo(jogada))
    print("=====================================\n")
    
    # Caso haja um vencedor o loop será encerrado
    if status_jogo(jogada) != "AINDA TEM JOGO":
        finalizar_jogo = True

[[ 0  1  0]
 [ 0  1  1]
 [-1 -1  0]]

Jogada realizada
[[ 1  1  0]
 [ 0  1  1]
 [-1 -1  0]]
AINDA TEM JOGO

Jogada realizada
[[ 1  1  0]
 [ 0  1  1]
 [-1 -1  1]]
X VENCEU!

